hardly_check = false
per_gov_check = false
tcp_bbr3_check = false
cachy_config_check = true
nconfig_check = false
xconfig_check = false
localmodcfg_check = false
use_current_check = false
builtin_zfs_check = false
builtin_nvidia_check = false
builtin_nvidia_open_check = false
build_debug_check = false
hz_ticks_combo = "250"
tickrate_combo = "full"
preempt_combo = "lazy"
hugepage_combo = "madvise"
lto_combo = "thin"
cpu_opt_combo = "native"
custom_name_edit = "linux-xps9300-bore"
